import { GitHubIssue } from '@/types/github.types';

// Mock data for fallback
export const mockIssues: GitHubIssue[] = [
    {
        id: 1,
        number: 42,
        title: "Add dark mode support to the dashboard",
        body: "Users have been requesting dark mode support. This would improve accessibility and user experience...",
        state: "open",
        created_at: "2024-01-15T10:30:00Z",
        updated_at: "2024-01-16T14:20:00Z",
        comments: 8,
        labels: [
            { name: "enhancement", color: "a2eeef" },
            { name: "good first issue", color: "7057ff" },
            { name: "help wanted", color: "008672" },
        ],
        user: {
            login: "developer123",
            avatar_url: "/placeholder.svg?height=40&width=40",
        },
        assignees: [
            { login: "developer123", avatar_url: "/placeholder.svg?height=40&width=40", id: 1 },
            { login: "designer456", avatar_url: "/placeholder.svg?height=40&width=40", id: 2 }
        ],
        repository: {
            name: "awesome-dashboard",
            full_name: "company/awesome-dashboard",
            owner: { login: "company" },
            stargazers_count: 1250,
            forks_count: 89,
            watchers_count: 1250,
            subscribers_count: 1250,
            open_issues_count: 12,
            language: "TypeScript",
            languages: ["TypeScript", "JavaScript", "CSS"],
            avatar_url: "/placeholder.svg?height=40&width=40"
        },
        html_url: "https://github.com/company/awesome-dashboard/issues/42",
    },
    {
        id: 2,
        number: 156,
        title: "Performance optimization for large datasets",
        body: "The application becomes slow when handling datasets with more than 10k records...",
        state: "open",
        created_at: "2024-01-14T09:15:00Z",
        updated_at: "2024-01-15T16:45:00Z",
        comments: 12,
        labels: [
            { name: "performance", color: "d73a49" },
            { name: "bug", color: "d73a49" },
            { name: "priority: high", color: "b60205" },
        ],
        user: {
            login: "performance-guru",
            avatar_url: "/placeholder.svg?height=40&width=40",
        },
        assignees: [
            { login: "performance-guru", avatar_url: "/placeholder.svg?height=40&width=40", id: 3 }
        ],
        repository: {
            name: "data-processor",
            full_name: "startup/data-processor",
            owner: { login: "startup" },
            stargazers_count: 890,
            forks_count: 45,
            watchers_count: 890,
            subscribers_count: 890,
            open_issues_count: 8,
            language: "Python",
            languages: ["Python", "Dockerfile"],
            avatar_url: "/placeholder.svg?height=40&width=40"
        },
        html_url: "https://github.com/startup/data-processor/issues/156",
    },
    {
        id: 3,
        number: 23,
        title: "Add support for custom themes",
        body: "Allow users to create and share custom themes for better personalization...",
        state: "open",
        created_at: "2024-01-13T14:22:00Z",
        updated_at: "2024-01-14T11:30:00Z",
        comments: 5,
        labels: [
            { name: "feature request", color: "a2eeef" },
            { name: "ui/ux", color: "0052cc" },
            { name: "good first issue", color: "7057ff" },
        ],
        user: {
            login: "designer-dev",
            avatar_url: "/placeholder.svg?height=40&width=40",
        },
        assignees: [],
        repository: {
            name: "theme-engine",
            full_name: "opensource/theme-engine",
            owner: { login: "opensource" },
            stargazers_count: 2100,
            forks_count: 156,
            watchers_count: 2100,
            subscribers_count: 2100,
            open_issues_count: 23,
            language: "JavaScript",
            languages: ["JavaScript", "HTML", "CSS"],
            avatar_url: "/placeholder.svg?height=40&width=40"
        },
        html_url: "https://github.com/opensource/theme-engine/issues/23",
    },
]

export const popularLanguages = [
    "JavaScript", "TypeScript", "Python", "Java", "C++", "C", "C#", "Go", "Rust",
    "PHP", "Ruby", "Swift", "Kotlin", "Dart", "R", "MATLAB", "Scala", "Perl",
    "Haskell", "Clojure", "Elixir", "Erlang", "Julia", "Lua", "Shell", "PowerShell",
    "Assembly", "Objective-C", "Vue", "React", "Angular", "Node.js", "HTML", "CSS",
    "SCSS", "Sass", "Less", "JSON", "YAML", "XML", "Markdown", "Dockerfile"
]

export const commonLabels = ["good first issue","💎 Bounty", "help wanted", "GSoC2025", "bug", "enhancement", "documentation"]

// Repository search constants
export const repositorySortOptions = [
    { value: 'stars', label: 'Most Stars' },
    { value: 'forks', label: 'Most Forks' },
    { value: 'help-wanted-issues', label: 'Most Help Wanted' },
    { value: 'updated', label: 'Recently Updated' },
    { value: 'created', label: 'Recently Created' }
] as const

export const repositoryOrderOptions = [
    { value: 'desc', label: 'Descending' },
    { value: 'asc', label: 'Ascending' }
] as const

export const repositoryLicenseOptions = [
    { value: 'mit', label: 'MIT' },
    { value: 'apache-2.0', label: 'Apache 2.0' },
    { value: 'gpl-3.0', label: 'GPL 3.0' },
    { value: 'gpl-2.0', label: 'GPL 2.0' },
    { value: 'bsd-3-clause', label: 'BSD 3-Clause' },
    { value: 'bsd-2-clause', label: 'BSD 2-Clause' },
    { value: 'lgpl-2.1', label: 'LGPL 2.1' },
    { value: 'lgpl-3.0', label: 'LGPL 3.0' },
    { value: 'mpl-2.0', label: 'Mozilla 2.0' },
    { value: 'unlicense', label: 'Unlicense' },
    { value: 'isc', label: 'ISC' },
    { value: 'agpl-3.0', label: 'AGPL 3.0' }
] as const

export const trendingTopics = [
    'artificial-intelligence', 'machine-learning', 'deep-learning', 'neural-networks',
    'blockchain', 'cryptocurrency', 'web3', 'defi',
    'react', 'vue', 'angular', 'svelte', 'nextjs', 'nuxt',
    'typescript', 'javascript', 'python', 'rust', 'go', 'swift',
    'kubernetes', 'docker', 'terraform', 'ansible',
    'mobile', 'ios', 'android', 'flutter', 'react-native',
    'devops', 'ci-cd', 'github-actions', 'gitlab-ci',
    'api', 'graphql', 'rest', 'microservices',
    'database', 'postgresql', 'mongodb', 'redis',
    'game-development', 'unity', 'unreal-engine', 'godot',
    'data-science', 'analytics', 'visualization', 'jupyter',
    'open-source', 'beginner-friendly', 'good-first-issue', 'hacktoberfest'
] as const

export const popularOrganizations = [
    'microsoft', 'google', 'facebook', 'apple', 'amazon', 'netflix', 'uber',
    'airbnb', 'spotify', 'twitter', 'github', 'gitlab', 'docker', 'kubernetes',
    'tensorflow', 'pytorch', 'openai', 'huggingface', 'vercel', 'supabase',
    'prisma', 'stripe', 'twilio', 'sendgrid', 'auth0', 'okta'
] as const

// Mock repository data for fallback
export const mockRepositories = [
    {
        id: 1,
        name: "awesome-nextjs",
        full_name: "vercel/awesome-nextjs",
        description: "A curated list of awesome Next.js resources, libraries, tools and more.",
        html_url: "https://github.com/vercel/awesome-nextjs",
        stargazers_count: 15000,
        watchers_count: 15000,
        language: "TypeScript",
        forks_count: 1200,
        created_at: "2020-01-15T10:30:00Z",
        updated_at: "2024-01-16T14:20:00Z",
        pushed_at: "2024-01-16T14:20:00Z",
        size: 2048,
        open_issues_count: 25,
        topics: ["nextjs", "react", "javascript", "typescript", "awesome-list"],
        license: {
            key: "mit",
            name: "MIT License",
            spdx_id: "MIT",
            url: "https://api.github.com/licenses/mit",
            node_id: "MDc6TGljZW5zZTEz"
        },
        default_branch: "main",
        archived: false,
        disabled: false,
        fork: false,
        private: false,
        visibility: "public",
        owner: {
            login: "vercel",
            id: 14985020,
            avatar_url: "https://avatars.githubusercontent.com/u/14985020?v=4",
            html_url: "https://github.com/vercel",
            type: "Organization"
        },
        clone_url: "https://github.com/vercel/awesome-nextjs.git",
        ssh_url: "git@github.com:vercel/awesome-nextjs.git",
        homepage: "https://awesome-nextjs.vercel.app",
        language_color: "#3178c6",
        languages: { "TypeScript": 85, "JavaScript": 15 },
        score: 1.0
    },
    {
        id: 2,
        name: "react",
        full_name: "facebook/react",
        description: "A declarative, efficient, and flexible JavaScript library for building user interfaces.",
        html_url: "https://github.com/facebook/react",
        stargazers_count: 220000,
        watchers_count: 220000,
        language: "JavaScript",
        forks_count: 45000,
        created_at: "2013-05-24T16:15:54Z",
        updated_at: "2024-01-16T12:00:00Z",
        pushed_at: "2024-01-16T12:00:00Z",
        size: 40960,
        open_issues_count: 800,
        topics: ["react", "javascript", "frontend", "ui", "virtual-dom"],
        license: {
            key: "mit",
            name: "MIT License",
            spdx_id: "MIT",
            url: "https://api.github.com/licenses/mit",
            node_id: "MDc6TGljZW5zZTEz"
        },
        default_branch: "main",
        archived: false,
        disabled: false,
        fork: false,
        private: false,
        visibility: "public",
        owner: {
            login: "facebook",
            id: 69631,
            avatar_url: "https://avatars.githubusercontent.com/u/69631?v=4",
            html_url: "https://github.com/facebook",
            type: "Organization"
        },
        clone_url: "https://github.com/facebook/react.git",
        ssh_url: "git@github.com:facebook/react.git",
        homepage: "https://reactjs.org",
        language_color: "#f7df1e",
        languages: { "JavaScript": 60, "TypeScript": 35, "C++": 5 },
        score: 1.0
    },
    {
        id: 3,
        name: "vue",
        full_name: "vuejs/vue",
        description: "Progressive JavaScript framework for building user interfaces.",
        html_url: "https://github.com/vuejs/vue",
        stargazers_count: 180000,
        watchers_count: 180000,
        language: "JavaScript",
        forks_count: 28000,
        created_at: "2013-07-29T03:24:51Z",
        updated_at: "2024-01-16T10:00:00Z",
        pushed_at: "2024-01-16T10:00:00Z",
        size: 30720,
        open_issues_count: 120,
        topics: ["vue", "javascript", "frontend", "framework", "progressive"],
        license: {
            key: "mit",
            name: "MIT License",
            spdx_id: "MIT",
            url: "https://api.github.com/licenses/mit",
            node_id: "MDc6TGljZW5zZTEz"
        },
        default_branch: "main",
        archived: false,
        disabled: false,
        fork: false,
        private: false,
        visibility: "public",
        owner: {
            login: "vuejs",
            id: 6128107,
            avatar_url: "https://avatars.githubusercontent.com/u/6128107?v=4",
            html_url: "https://github.com/vuejs",
            type: "Organization"
        },
        clone_url: "https://github.com/vuejs/vue.git",
        ssh_url: "git@github.com:vuejs/vue.git",
        homepage: "https://vuejs.org",
        language_color: "#f7df1e",
        languages: { "JavaScript": 70, "TypeScript": 25, "Vue": 5 },
        score: 1.0
    },
    {
        id: 4,
        name: "angular",
        full_name: "angular/angular",
        description: "The modern web developer's platform.",
        html_url: "https://github.com/angular/angular",
        stargazers_count: 95000,
        watchers_count: 95000,
        language: "TypeScript",
        forks_count: 25000,
        created_at: "2014-09-18T16:12:01Z",
        updated_at: "2024-01-16T08:00:00Z",
        pushed_at: "2024-01-16T08:00:00Z",
        size: 51200,
        open_issues_count: 200,
        topics: ["angular", "typescript", "framework", "web", "mobile"],
        license: {
            key: "mit",
            name: "MIT License",
            spdx_id: "MIT",
            url: "https://api.github.com/licenses/mit",
            node_id: "MDc6TGljZW5zZTEz"
        },
        default_branch: "main",
        archived: false,
        disabled: false,
        fork: false,
        private: false,
        visibility: "public",
        owner: {
            login: "angular",
            id: 139426,
            avatar_url: "https://avatars.githubusercontent.com/u/139426?v=4",
            html_url: "https://github.com/angular",
            type: "Organization"
        },
        clone_url: "https://github.com/angular/angular.git",
        ssh_url: "git@github.com:angular/angular.git",
        homepage: "https://angular.io",
        language_color: "#3178c6",
        languages: { "TypeScript": 80, "JavaScript": 15, "HTML": 5 },
        score: 1.0
    },
    {
        id: 5,
        name: "node",
        full_name: "nodejs/node",
        description: "Node.js JavaScript runtime built on Chrome's V8 JavaScript engine.",
        html_url: "https://github.com/nodejs/node",
        stargazers_count: 110000,
        watchers_count: 110000,
        language: "JavaScript",
        forks_count: 30000,
        created_at: "2009-05-27T19:30:26Z",
        updated_at: "2024-01-16T06:00:00Z",
        pushed_at: "2024-01-16T06:00:00Z",
        size: 40960,
        open_issues_count: 150,
        topics: ["nodejs", "javascript", "runtime", "v8", "server"],
        license: {
            key: "mit",
            name: "MIT License",
            spdx_id: "MIT",
            url: "https://api.github.com/licenses/mit",
            node_id: "MDc6TGljZW5zZTEz"
        },
        default_branch: "main",
        archived: false,
        disabled: false,
        fork: false,
        private: false,
        visibility: "public",
        owner: {
            login: "nodejs",
            id: 9950313,
            avatar_url: "https://avatars.githubusercontent.com/u/9950313?v=4",
            html_url: "https://github.com/nodejs",
            type: "Organization"
        },
        clone_url: "https://github.com/nodejs/node.git",
        ssh_url: "git@github.com:nodejs/node.git",
        homepage: "https://nodejs.org",
        language_color: "#f7df1e",
        languages: { "JavaScript": 60, "C++": 25, "Python": 10, "Shell": 5 },
        score: 1.0
    },
    {
        id: 6,
        name: "tensorflow",
        full_name: "tensorflow/tensorflow",
        description: "An Open Source Machine Learning Framework for Everyone.",
        html_url: "https://github.com/tensorflow/tensorflow",
        stargazers_count: 190000,
        watchers_count: 190000,
        language: "Python",
        forks_count: 20000,
        created_at: "2015-11-07T01:19:20Z",
        updated_at: "2024-01-16T04:00:00Z",
        pushed_at: "2024-01-16T04:00:00Z",
        size: 81920,
        open_issues_count: 300,
        topics: ["tensorflow", "machine-learning", "deep-learning", "neural-networks", "ai"],
        license: {
            key: "apache-2.0",
            name: "Apache License 2.0",
            spdx_id: "Apache-2.0",
            url: "https://api.github.com/licenses/apache-2.0",
            node_id: "MDc6TGljZW5zZTEz"
        },
        default_branch: "main",
        archived: false,
        disabled: false,
        fork: false,
        private: false,
        visibility: "public",
        owner: {
            login: "tensorflow",
            id: 15658638,
            avatar_url: "https://avatars.githubusercontent.com/u/15658638?v=4",
            html_url: "https://github.com/tensorflow",
            type: "Organization"
        },
        clone_url: "https://github.com/tensorflow/tensorflow.git",
        ssh_url: "git@github.com:tensorflow/tensorflow.git",
        homepage: "https://tensorflow.org",
        language_color: "#3776ab",
        languages: { "Python": 70, "C++": 20, "JavaScript": 5, "Shell": 5 },
        score: 1.0
    },
    {
        id: 7,
        name: "pytorch",
        full_name: "pytorch/pytorch",
        description: "Tensors and Dynamic neural networks in Python with strong GPU acceleration",
        html_url: "https://github.com/pytorch/pytorch",
        stargazers_count: 75000,
        watchers_count: 75000,
        language: "Python",
        forks_count: 20000,
        created_at: "2016-08-01T00:00:00Z",
        updated_at: "2024-01-16T02:00:00Z",
        pushed_at: "2024-01-16T02:00:00Z",
        size: 102400,
        open_issues_count: 400,
        topics: ["pytorch", "machine-learning", "deep-learning", "neural-networks", "ai", "python"],
        license: {
            key: "bsd-3-clause",
            name: "BSD 3-Clause License",
            spdx_id: "BSD-3-Clause",
            url: "https://api.github.com/licenses/bsd-3-clause",
            node_id: "MDc6TGljZW5zZTEz"
        },
        default_branch: "main",
        archived: false,
        disabled: false,
        fork: false,
        private: false,
        visibility: "public",
        owner: {
            login: "pytorch",
            id: 21003710,
            avatar_url: "https://avatars.githubusercontent.com/u/21003710?v=4",
            html_url: "https://github.com/pytorch",
            type: "Organization"
        },
        clone_url: "https://github.com/pytorch/pytorch.git",
        ssh_url: "git@github.com:pytorch/pytorch.git",
        homepage: "https://pytorch.org",
        language_color: "#3776ab",
        languages: { "Python": 60, "C++": 30, "CUDA": 5, "Shell": 5 },
        score: 1.0
    },
    {
        id: 8,
        name: "kubernetes",
        full_name: "kubernetes/kubernetes",
        description: "Production-Grade Container Scheduling and Management",
        html_url: "https://github.com/kubernetes/kubernetes",
        stargazers_count: 105000,
        watchers_count: 105000,
        language: "Go",
        forks_count: 38000,
        created_at: "2014-06-07T00:00:00Z",
        updated_at: "2024-01-16T00:00:00Z",
        pushed_at: "2024-01-16T00:00:00Z",
        size: 204800,
        open_issues_count: 500,
        topics: ["kubernetes", "containers", "orchestration", "cloud-native", "devops"],
        license: {
            key: "apache-2.0",
            name: "Apache License 2.0",
            spdx_id: "Apache-2.0",
            url: "https://api.github.com/licenses/apache-2.0",
            node_id: "MDc6TGljZW5zZTEz"
        },
        default_branch: "main",
        archived: false,
        disabled: false,
        fork: false,
        private: false,
        visibility: "public",
        owner: {
            login: "kubernetes",
            id: 13629408,
            avatar_url: "https://avatars.githubusercontent.com/u/13629408?v=4",
            html_url: "https://github.com/kubernetes",
            type: "Organization"
        },
        clone_url: "https://github.com/kubernetes/kubernetes.git",
        ssh_url: "git@github.com:kubernetes/kubernetes.git",
        homepage: "https://kubernetes.io",
        language_color: "#00ADD8",
        languages: { "Go": 80, "Shell": 10, "Python": 5, "Makefile": 5 },
        score: 1.0
    },
    {
        id: 9,
        name: "docker",
        full_name: "docker/docker",
        description: "Docker - the open-source application container engine",
        html_url: "https://github.com/docker/docker",
        stargazers_count: 68000,
        watchers_count: 68000,
        language: "Go",
        forks_count: 20000,
        created_at: "2013-01-18T21:30:00Z",
        updated_at: "2024-01-15T22:00:00Z",
        pushed_at: "2024-01-15T22:00:00Z",
        size: 153600,
        open_issues_count: 200,
        topics: ["docker", "containers", "containerization", "devops", "microservices"],
        license: {
            key: "apache-2.0",
            name: "Apache License 2.0",
            spdx_id: "Apache-2.0",
            url: "https://api.github.com/licenses/apache-2.0",
            node_id: "MDc6TGljZW5zZTEz"
        },
        default_branch: "main",
        archived: false,
        disabled: false,
        fork: false,
        private: false,
        visibility: "public",
        owner: {
            login: "docker",
            id: 5429470,
            avatar_url: "https://avatars.githubusercontent.com/u/5429470?v=4",
            html_url: "https://github.com/docker",
            type: "Organization"
        },
        clone_url: "https://github.com/docker/docker.git",
        ssh_url: "git@github.com:docker/docker.git",
        homepage: "https://docker.com",
        language_color: "#00ADD8",
        languages: { "Go": 70, "Shell": 15, "Python": 10, "Makefile": 5 },
        score: 1.0
    },
    {
        id: 10,
        name: "flutter",
        full_name: "flutter/flutter",
        description: "Flutter makes it easy and fast to build beautiful apps for mobile and beyond",
        html_url: "https://github.com/flutter/flutter",
        stargazers_count: 160000,
        watchers_count: 160000,
        language: "Dart",
        forks_count: 25000,
        created_at: "2015-05-20T00:00:00Z",
        updated_at: "2024-01-15T20:00:00Z",
        pushed_at: "2024-01-15T20:00:00Z",
        size: 307200,
        open_issues_count: 600,
        topics: ["flutter", "dart", "mobile", "cross-platform", "ui-framework"],
        license: {
            key: "bsd-3-clause",
            name: "BSD 3-Clause License",
            spdx_id: "BSD-3-Clause",
            url: "https://api.github.com/licenses/bsd-3-clause",
            node_id: "MDc6TGljZW5zZTEz"
        },
        default_branch: "main",
        archived: false,
        disabled: false,
        fork: false,
        private: false,
        visibility: "public",
        owner: {
            login: "flutter",
            id: 14101776,
            avatar_url: "https://avatars.githubusercontent.com/u/14101776?v=4",
            html_url: "https://github.com/flutter",
            type: "Organization"
        },
        clone_url: "https://github.com/flutter/flutter.git",
        ssh_url: "git@github.com:flutter/flutter.git",
        homepage: "https://flutter.dev",
        language_color: "#0175C2",
        languages: { "Dart": 85, "C++": 10, "Shell": 3, "Python": 2 },
        score: 1.0
    }
]
